mock:
	mockgen --source=internal/repository/auth.go --destination=mock/repository/auth.go --package mock

docker-build:
	docker-compose build

docker-up:
	docker-compose up -d

docker-down:
	docker-compose down